{
 "title": "Galaxy Database",
 "tags": [
  "migrated",
  "infrastructure"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "tables",
    "label": "Tables",
    "query": "show tag values with key = \"relname\""
   }
  ]
 },
 "panels": [
  { "title": "Overall metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_db]]:commit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "[[tag_db]]:rollback",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_rollback" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "measurement",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "100" ], "type": "bottom" }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "!=", "value": "FETCH" }
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "!=", "value": "FETCH" }
     ]
    },
    {
     "alias": "95",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "!=", "value": "FETCH" }
     ]
    },
    {
     "alias": "median",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "!=", "value": "FETCH" }
     ]
    },
    {
     "alias": "mean",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "!=", "value": "FETCH" }
     ]
    }
   ]
  },
  {
   "title": "Command Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "[[tag_command]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "alloc" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_clean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "clean" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_backend" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "backend" ], "type": "alias" }
      ],
      [
       { "params": [ "buffers_backend_fsync" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "backend_sync" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backends",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_db]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_usename]] to [[tag_datname]] ([[tag_state]])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "usename" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql_custom",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuples Modified",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "deleted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_inserted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "inserted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_updated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "updated" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuples Fetched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "fetched" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_returned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "returned" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "blk_hit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "blks_hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" },
       { "params": [ "blocks hit" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "blk_read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "[[tag_db]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Query Times by Command",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_command]]",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Median Query Times by Command",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_command]]",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "99th Percentile Query Times by Command",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_command]]",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_query_time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  { "title": "Table Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Current Table Size",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql_table_sizes",
     "select": [
      [
       { "params": [ "table_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "table_size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Index Size",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql_table_sizes",
     "select": [
      [
       { "params": [ "index_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "index_size" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Table Sizes Change Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 59 },
     "repeat": "tables",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 59 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 59 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 66 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 66 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 66 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 73 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 73 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 73 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    },
    {
     "title": "$tables size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 73 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "table_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "table_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      },
      {
       "alias": "index_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "postgresql_table_sizes",
       "select": [
        [
         { "params": [ "index_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "table_size" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "relname", "operator": "=~", "value": "/^$tables$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}