{
 "title": "Alerts",
 "description": "Various admin-important alerts related to the infrastructure",
 "tags": [ "infrastructure" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Important Things", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk IO time sn04",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    },
    {
     "alias": "combined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/sd.1/" }
     ]
    }
   ]
  },
  {
   "title": "Jobs queued but lacking cluster ID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_group]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobs-queued",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Ansible Status",
   "type": "text",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 1 },
   "content": "Server | Playbook\n--- | ---\nApollo | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fapollo)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/apollo/)\nBuild  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fbuild)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/build/)\nCVMFS  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fcvmfs)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/cvmfs/)\nDocker  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fdocker)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/docker/)\nGalaxy  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fgalaxy)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/galaxy/)\nGalaxy Test  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fgalaxy-test)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/galaxy-test/)\nStats  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fstats)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/stats/)\nProxy  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fhaproxy-internal)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/haproxy-internal/)\nInflux |  [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Finfluxdb)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/influxdb/)\nTelescope  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Ftelescope)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/telescope/)\n  \n\n"
  },
  {
   "title": "Jobs queued but lacking cluster ID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_handler]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "handler" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jobs-queued-internal-by-handler",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job states",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Workflow Invocation States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_handler]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "handler" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "workflow-invocation-status",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "uWSGI Socket queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uwsgi.general",
     "select": [
      [
       { "params": [ "listen_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SSL Cert Expiration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ssl.expiry",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seconds since last log message",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_service]] on [[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "journalctl.lastlog",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Journalctl Queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_query]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "journalctl",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/vgcnbwc/" }
     ]
    },
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/vgcnbwc/" }
     ]
    }
   ]
  },
  {
   "title": "CVMFS Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_repo]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "cvmfs1-iu0.galaxyproject.org" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (NFS Mounts)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "=", "value": "nfs" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" },
      { "condition": "OR", "key": "fstype", "operator": "=", "value": "nfs4" }
     ]
    }
   ]
  },
  {
   "title": "Emails",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]] - [[tag_luser]]",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "luser" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1d" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job per handler",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "handler" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" },
      { "condition": "AND", "key": "handler", "operator": "=~", "value": "/handler_main/" }
     ]
    }
   ]
  },
  {
   "title": "Uninteresting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 2, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "[[tag_domain]]: [[tag_server]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "domain" ], "type": "tag" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "dns_query",
       "select": [
        [
         { "params": [ "query_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Dropped packets",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_host]]:[[tag_interface]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "$__interval" ], "type": "non_negative_derivative" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Usage (Cloud)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_host]]:[[tag_path]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "fstype", "operator": "!=", "value": "nfs" },
        { "condition": "AND", "key": "fstype", "operator": "!=", "value": "nfs4" },
        { "condition": "AND", "key": "fstype", "operator": "!=", "value": "devtmpfs" },
        { "condition": "AND", "key": "fstype", "operator": "!=", "value": "tmpfs" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^vgcn/" }
       ]
      }
     ]
    },
    {
     "title": "Request Timings",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "alias": "[[tag_page]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "usegalaxy-eu.pages",
       "select": [
        [
         { "params": [ "request_time" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "page", "operator": "=", "value": "home" }
       ]
      },
      {
       "alias": "[[tag_service]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "service" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "usegalaxy-eu.services",
       "select": [
        [
         { "params": [ "request_time" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^ftp/" }
       ]
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 4, "x": 2, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Usage (Non-Cloud / Local Drives)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 9, "x": 15, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_host]]:[[tag_path]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "path" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "5" ], "type": "moving_average" }
        ]
       ],
       "tags": [
        { "key": "fstype", "operator": "!=", "value": "nfs" },
        { "condition": "AND", "key": "fstype", "operator": "!=", "value": "nfs4" },
        { "condition": "AND", "key": "fstype", "operator": "!=", "value": "devtmpfs" },
        { "condition": "AND", "key": "fstype", "operator": "!=", "value": "tmpfs" },
        { "condition": "AND", "key": "host", "operator": "!~", "value": "/^vgcn/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}