{
 "title": "Alerts",
 "description": "Various admin-important alerts related to the infrastructure",
 "tags": [ "infrastructure" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Important Things", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "[[tag_page]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "usegalaxy-eu.pages",
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "page", "operator": "=", "value": "home" }
     ]
    },
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "usegalaxy-eu.services",
     "select": [
      [
       { "params": [ "request_time" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^ftp/" }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_domain]]: [[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Journalctl Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_query]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "query" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "journalctl",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO time sn04",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    },
    {
     "alias": "combined",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/sd.1/" }
     ]
    }
   ]
  },
  {
   "title": "CVMFS Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_repo]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "repo" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seconds since last log message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "[[tag_service]] on [[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "journalctl.lastlog",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workflow Invocation States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_handler]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "handler" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "workflow-invocation-status",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Uninteresting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/vgcnbwc/" }
     ]
    },
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/vgcnbwc/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (Non-Cloud / Local Drives)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]:[[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "!=", "value": "nfs" },
      { "condition": "AND", "key": "fstype", "operator": "!=", "value": "nfs4" },
      { "condition": "AND", "key": "fstype", "operator": "!=", "value": "devtmpfs" },
      { "condition": "AND", "key": "fstype", "operator": "!=", "value": "tmpfs" },
      { "condition": "AND", "key": "host", "operator": "!~", "value": "/^vgcn/" }
     ]
    }
   ]
  },
  {
   "title": "SSL Cert Expiration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ssl.expiry",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (NFS Mounts)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "=", "value": "nfs" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" },
      { "condition": "OR", "key": "fstype", "operator": "=", "value": "nfs4" }
     ]
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]:[[tag_interface]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage (Cloud)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]:[[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "fstype", "operator": "!=", "value": "nfs" },
      { "condition": "AND", "key": "fstype", "operator": "!=", "value": "nfs4" },
      { "condition": "AND", "key": "fstype", "operator": "!=", "value": "devtmpfs" },
      { "condition": "AND", "key": "fstype", "operator": "!=", "value": "tmpfs" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^vgcn/" }
     ]
    }
   ]
  },
  {
   "title": "Emails",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]] - [[tag_luser]]",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "luser" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1d" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}