{
 "title": "BY-COVID",
 "description": "Dashboard for ELIXIR monitoring",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Registered Users Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-users.upto",
     "query": "SELECT last(\"count\") FROM \"server-users.upto\" WHERE $timeFilter GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": {
    "content": "<img src=\"https://raw.githubusercontent.com/usegalaxy-eu/website/master/assets/media/BYCOVID_logo.png\" alt=\"BY-COVID\" style=\"\"/>"
   }
  },
  {
   "title": "Jobs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-jobs.upto",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-jobs",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 7 },
   "options": {
    "content": "<br/>\n\n# [BY-COVID](https://by-covid.org/)\n\nThe BeYond-COVID project aims to make COVID-19 data accessible to scientists in laboratories but also\nto anyone who can use it, such as medical staff in hospitals or government officials.\n\nGoing beyond SARS-CoV-2 data, the project will provide a framework for making data from\nother infectious diseases open and accessible to everyone.\n\nThe [European Galaxy Server](https://usegalaxy.eu) is used by users beyond BY-COVID and covers other\nuser cases as well. The numbers shown here are a aggregation from the overall usage.\n\n\n"
   }
  },
  {
   "title": "Workflow Invocations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-users",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Datasets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-datasets",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflows",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ELIXIR AAI Users",
   "type": "stat",
   "description": "Users that used the [ELIXIR AAI](https://elixir-europe.org/services/compute/aai) (Authentication and Authorisation Infrastructure) to log into the European Galaxy server.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "provider" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "users-with-oidc",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Users (last 10 minutes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "journalctl.activeusers",
     "query": "SELECT \"users\" FROM \"active_users\" WHERE (\"host\" = 'sn06.galaxyproject.eu') AND $timeFilter GROUP BY \"timespan\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}