{
 "title": "Cluster Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 }, "options": { "content": "# Cluster Utilization" } },
  {
   "title": "Overall cluster resource utilization",
   "type": "bargauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"claimed_slots\") AS \"Claimed slots\", \"total_slots\" AS \"Total slots\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'compute') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_slots" ], "type": "field" },
       { "params": [ "Total slots" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute" }
     ]
    }
   ]
  },
  {
   "title": "Claimed Memory (in TiB)",
   "type": "bargauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_memory\")  /(1024 * 1024) AS \"Total mem (TiB)\", last(\"claimed_memory\")  /(1024*1024) AS \"Claimed mem (TiB)\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'compute') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024 * 1024)" ], "type": "math" },
       { "params": [ "Total mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Claimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Unclaimed mem (TiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute" }
     ]
    }
   ]
  },
  {
   "title": "Claimed CPU Cores",
   "type": "bargauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_cpus\") AS \"Total CPU cores\", last(\"claimed_cpus\") AS \"Claimed CPU cores\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'compute') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024 * 1024)" ], "type": "math" },
       { "params": [ "Total mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Claimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Unclaimed mem (TiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute" }
     ]
    }
   ]
  },
  {
   "title": "Claimed GPUs (NVIDIA Tesla T4)",
   "type": "bargauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute GPU",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "query": "SELECT last(\"total_slots\") AS \"Total slots\", last(\"claimed_slots\") AS \"Claimed slots\" FROM \"htcondor_cluster_usage\" WHERE (\"classad\" = '\\'cluster\\'' AND \"group\" = 'compute_gpu') AND $timeFilter GROUP BY time($__interval), \"group\"",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Total mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /1024" ], "type": "math" },
       { "params": [ "Claimed mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Unclaimed mem (GiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute_gpu" }
     ]
    }
   ]
  }
 ]
}