{
 "title": "CVMFS Stratum 1 Server Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repos",
    "label": "CVMFS Repo",
    "query": "SHOW TAG VALUES FROM \"cvmfs.status\" WITH KEY = \"repo\""
   },
   {
    "name": "servers",
    "label": "CVMFS Server",
    "query": "SHOW TAG VALUES FROM \"cvmfs.status\" WITH KEY = \"server\""
   }
  ]
 },
 "panels": [
  { "title": "$servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "servers" },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 0, "y": 1 },
   "repeat": "repos",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  { "title": "$servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 0, "y": 4 },
   "repeat": "repos",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  { "title": "$servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 0, "y": 7 },
   "repeat": "repos",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  { "title": "$servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 0, "y": 10 },
   "repeat": "repos",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  { "title": "$servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 0, "y": 13 },
   "repeat": "repos",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  { "title": "$servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 0, "y": 16 },
   "repeat": "repos",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$servers$/" }
     ]
    }
   ]
  },
  { "title": "Repository Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 0, "y": 19 },
   "repeat": "repos",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  { "title": "Repository Revision", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 0, "y": 25 },
   "repeat": "repos",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "rev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "rev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "rev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "rev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "rev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "rev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  {
   "title": "$repos",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cvmfs.status",
     "select": [
      [
       { "params": [ "rev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=~", "value": "/^$repos$/" }
     ]
    }
   ]
  },
  { "title": "EU Stratum1 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Hits (% of requests)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "5m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "squid.cache",
     "select": [
      [
       { "params": [ "hits_perc_reqs_5m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      }
     ]
    },
    {
     "alias": "60m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "squid.cache",
     "select": [
      [
       { "params": [ "hits_perc_reqs_5m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      }
     ]
    }
   ]
  },
  {
   "title": "Hits (% of requests)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HTTP Requests / Minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "squid.conn",
     "select": [
      [
       { "params": [ "avg_http_per_minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      }
     ]
    },
    {
     "alias": "ICP Requests / Minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "squid.conn",
     "select": [
      [
       { "params": [ "avg_icp_per_minute" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      }
     ]
    }
   ]
  },
  {
   "title": "Hit & Miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "squid.timing",
     "select": [
      [
       { "params": [ "cache_hits_5m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      }
     ]
    },
    {
     "alias": "Misses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "squid.timing",
     "select": [
      [
       { "params": [ "cache_miss_5m" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      },
      { "condition": "AND", "key": "fstype", "operator": "=", "value": "nfs" }
     ]
    }
   ]
  },
  {
   "title": "Hot Object Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Items",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "squid.ids",
     "select": [
      [
       { "params": [ "hot_obj_cache_items" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "cvmfs1-ufr0.internal.galaxyproject.eu"
      }
     ]
    }
   ]
  }
 ]
}