{
 "title": "day-to-day",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jwd_max",
    "query": "SELECT last(\"total\")  / (1024*1024*1024*1024) FROM \"disk\" WHERE (\"host\" = 'sn06.galaxyproject.eu' AND \"device\" =~ /^.*jwd*/) AND $timeFilter GROUP BY \"device\""
   },
   {
    "name": "Schedd",
    "query": "SHOW TAG VALUES FROM \"cluster.queue\" WITH KEY = \"schedd\""
   }
  ]
 },
 "panels": [
  { "title": "Galaxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job queue - current status",
   "type": "stat",
   "description": "Gives an overview of the current status of the Galaxy job queue.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "galaxy_job_queue_states_stats",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_state", "operator": "=", "value": "new" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "galaxy_job_queue_states_stats",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_state", "operator": "=", "value": "queued" }
     ]
    },
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "galaxy_job_queue_states_stats",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_state", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": "Job queue",
   "type": "graph",
   "description": "Time-series showing the status of Galaxy jobs.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'queued') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "queued" }
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'new') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "Jobs per handler - Overview",
   "type": "table",
   "description": "Shows the number of jobs handled by each job handler. Each job handler is run as a systemd service.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "handler" ], "type": "tag" }
     ],
     "measurement": "galaxy_jobs_per_handler_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": " Queued jobs (with or without condor ids) - current status",
   "type": "stat",
   "description": "Shows the distribution of jobs in the queued state, categorized as processed and unprocessed depending on whether they have received an external  (HTCondor) ID or not.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_group]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "jobs-queued",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": " Queued jobs (with or without condor ids)",
   "type": "graph",
   "description": "Shows the distribution of jobs in the queued state, categorized as processed and unprocessed depending on whether they have received an external  (HTCondor) ID or not.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_group]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "jobs-queued",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Jobs per destination - Overview",
   "type": "table",
   "description": "Gives an overview of the number of running and queued jobs per destination.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "destination_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "queue_by_destination",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy JWDs - Overview",
   "type": "barchart",
   "description": "Shows the storage overview of Galaxy JWD's. ",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (1024*1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^.*jwd*/" }
     ]
    },
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (1024*1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^.*jwd*/" }
     ]
    },
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / (1024*1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^.*jwd*/" }
     ]
    }
   ]
  },
  {
   "title": "Active Users (10 minutes)",
   "type": "stat",
   "description": "Shows the number of currently active users who are logged in on the usegalaxy.eu website.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "active_users",
     "query": "SELECT \"users\" FROM \"active_users\" WHERE (\"host\" = 'sn06.galaxyproject.eu') AND $timeFilter GROUP BY \"timespan\"",
     "select": [
      [
       { "params": [ "users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Gunicorn handlers last log entry",
   "type": "stat",
   "description": "Shows the number of seconds since the last log entry. If the entry was a bit old then the respective handler might have some issues. So, this helps to investigate the corresponding handler. Each handler is run as a systemd service.",
   "gridPos": { "h": 5, "w": 11, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "journalctl.lastlog",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/galaxy-handler@[0-5]$/" }
     ]
    }
   ]
  },
  {
   "title": "(WIP) Status of all critical services ",
   "type": "timeseries",
   "description": "This panel shows the list of services (e.g., tusd, celery, Galaxy, rabbitmq, etc.) and their statuses.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 22 }
  },
  { "title": "HTCondor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "HTCondor job queue - overview",
   "type": "graph",
   "description": "Gives an overview of the current status of the jobs in the HTCondor queue.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "cluster.queue",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" },
      { "condition": "AND", "key": "schedd", "operator": "=~", "value": "/^$Schedd$/" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor job queue - overview",
   "type": "stat",
   "description": "Gives an overview of the current status of the jobs in the HTCondor queue.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "schedd" ], "type": "tag" }
     ],
     "measurement": "cluster.queue",
     "query": "SELECT mean(\"count\") FROM \"cluster.queue\" WHERE (\"host\" = 'maintenance.galaxyproject.eu' AND \"schedd\" = 'sn06.galaxyproject.eu') AND $timeFilter GROUP BY time($__interval), \"state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" },
      { "condition": "AND", "key": "schedd", "operator": "=~", "value": "/^$Schedd$/" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy utilization of HTCondor cluster - Overview",
   "type": "gauge",
   "description": "Shows the resource utilization of the entire HTCondor  cluster utilization by Galaxy",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "select": [
      [
       { "params": [ "total_detected_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/(1024*1024)" ], "type": "math" },
       { "params": [ "Total mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Claimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/(1024*1024)" ], "type": "math" },
       { "params": [ "Unclaimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "total_gpu_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_gpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_gpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed GPU slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_busy_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed busy slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_idle_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed idle slots" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'machine'" }
     ]
    }
   ]
  },
  {
   "title": "Condor queued jobs and their status",
   "type": "table",
   "description": "This panel shows the real-time information of the condor queue. It also shows the compute resources requested by the job, when it was submitted to the queue, and when it started. \n\nNote:\n1. *undefined => The respective data was unavailable because the job had not yet started or was on hold or idle.\n2. Sometimes, request memory could be more than defined for the tool in the TPV tools.yml or the TPV shared database because we have a dedicated script that resubmits the job if it needs more memory up to a certain number of times.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "clusterid" ], "type": "tag" }
     ],
     "measurement": "condor_queued_jobs_status",
     "select": [
      [
       { "params": [ "jobstatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Status" ], "type": "alias" }
      ],
      [
       { "params": [ "cmd" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cmd" ], "type": "alias" }
      ],
      [
       { "params": [ "jobdescription" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Description" ], "type": "alias" }
      ],
      [
       { "params": [ "remotehost" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Remote Host" ], "type": "alias" }
      ],
      [
       { "params": [ "requestcpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Request CPUs (cores)" ], "type": "alias" }
      ],
      [
       { "params": [ "requestmemory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024" ], "type": "math" },
       { "params": [ "Request Memory (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "qdate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Queued Date" ], "type": "alias" }
      ],
      [
       { "params": [ "jobstartdate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Start Date" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "schedd", "operator": "=~", "value": "/^$Schedd$/" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster slots per group",
   "type": "stat",
   "description": "Shows the dynamic slots distribution across different groups (only important groups are shown). This gives an idea of what slots are available and free.",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_group - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Compute",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute.",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024 * 1024)" ], "type": "math" },
       { "params": [ "Total mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Claimed mem (TiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /(1024*1024)" ], "type": "math" },
       { "params": [ "Unclaimed mem (TiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Compute GPU",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Compute GPU",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Total mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /1024" ], "type": "math" },
       { "params": [ "Claimed mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Unclaimed mem (GiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "compute_gpu" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Interactive",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Interactive",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Total mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /1024" ], "type": "math" },
       { "params": [ "Claimed mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Unclaimed mem (GiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "interactive" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor cluster resource utilization of GalaxyGroup Upload",
   "type": "gauge",
   "description": "Shows the resource utilization of the HTCondor cluster GalaxyGroup Upload",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "htcondor_cluster_usage",
     "select": [
      [
       { "params": [ "total_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total slots" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed slots" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Claimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unclaimed CPU cores" ], "type": "alias" }
      ],
      [
       { "params": [ "total_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Total mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "claimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /1024" ], "type": "math" },
       { "params": [ "Claimed mem (GiB)" ], "type": "alias" }
      ],
      [
       { "params": [ "unclaimed_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1024" ], "type": "math" },
       { "params": [ "Unclaimed mem (GiB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "classad", "operator": "=", "value": "'cluster'" },
      { "condition": "AND", "key": "group", "operator": "=", "value": "upload" }
     ]
    }
   ]
  },
  { "title": "BWCloud", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Active nodes",
   "type": "gauge",
   "description": "Shows the count of the ones that are present in each zone (HTCondor cluster, BWCloud and the resources.yaml in VGCN infrastructure repo).",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(htcondor) AS \"HTCondor\" from vgcn_monitoring WHERE time >= now() - 30m and time <= now() and htcondor=true"
    },
    {
     "query": "SELECT count(bwcloud) AS \"BWCloud\" from vgcn_monitoring WHERE time >= now() - 30m and time <= now() and bwcloud=true"
    },
    {
     "query": "SELECT count(resource_def) AS \"VGCN definition\" from vgcn_monitoring WHERE time >= now() - 30m and time <= now() and resource_def=true"
    }
   ]
  },
  {
   "title": "BWCloud VMs and Servers root FS ('/') usage",
   "type": "table",
   "description": "Shows the root file system usage of Galaxy's BWCloud VMs (service and worker VMs) and servers.",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT d1.host AS Hosts, d1.path AS \"Root file system\", d1.used_percent AS \"Used percentage\" FROM disk AS d1 WHERE d1.path = '/'",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  { "title": "sn06 server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Current Disk Usage",
   "type": "table-old",
   "description": "Shows the sn06's (Galaxy master node) current disk usage",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 88 },
   "targets": [
    {
     "alias": "[[tag_fstype]] @ [[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"used_percent\") FROM \"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"fstype\", \"path\" fill(none)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Shows the sn06's (Galaxy master node) CPU utilization",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "guest" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "user" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Shows the sn06's (Galaxy master node) memory usage",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffered" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cached" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Server load",
   "type": "graph",
   "description": "Shows the sn06's (Galaxy master node) 1, 5, and 15 minute load average",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "IO Time",
   "type": "graph",
   "description": "Shows the sn06's (Galaxy master node) current disk IO",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  { "title": "Jenkins Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Build status",
   "type": "text",
   "description": "Shows the current status of the respective build jobs. \n\nNote: The user viewing this panel should have at least read access to the respective build jobs to view the actual status and should have logged in to the Jenkins UI.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 103 },
   "options": {
    "content": "Build job | Status\n--- | ---\napollo                 | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fapollo)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/apollo/)\nbuild                  | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fbuild)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/build/)\nbeacon                 | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fbeacon)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/beacon/)\nbeacon-import          | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fbeacon-import)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/beacon-import/)\ncelery                 | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fcelery)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/celery/)\ncvmfs1                 | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fcvmfs1)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/cvmfs1/)\ninfluxdb               | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Finfluxdb)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/influxdb/)\nmaintenance            | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fmaintenance)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/maintenance/)\nmq                     | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fmq)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/mq/)\nsn05\t               | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fsn05)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/sn05/)\nsn06\t               | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fsn06)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/sn06/)\nsn07                   | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fsn07)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/sn07/)\ntelescope              | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Ftelescope)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/telescope/)\nupload      \t\t   | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fplaybooks%2Fupload)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/upload/)\ninfrastructure         | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Finfrastructure)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/infrastructure/)\ninfrastructure-pr      | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Finfrastructure-pr)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/infrastructure-pr/)\ninstall-tools          | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Finstall-tools)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/install-tools/)\nquota-sync             | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fquota-sync)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/quota-sync/)\nvgcn-bwcloud-gpu-image | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fvgcn-bwcloud-gpu-image)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/vgcn-bwcloud-gpu-image/)\nvgcn-bwcloud-image\t   | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fvgcn-bwcloud-image)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/vgcn-bwcloud-image/)\nvgcn-infrastructure    | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fvgcn-infrastructure)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/vgcn-infrastructure/)\nwebsite\t               | [![Build Status](https://build.galaxyproject.eu/buildStatus/icon?job=usegalaxy-eu%2Fwebsite)](https://build.galaxyproject.eu/job/usegalaxy-eu/job/website/)\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}