{
 "title": "de.NBI",
 "description": "Dashboard for ELIXIR monitoring",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Registered Users Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-users.upto",
     "query": "SELECT last(\"count\") FROM \"server-users.upto\" WHERE $timeFilter GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": {
    "content": "<br/>\n<br/>\n<br/>\n<div style=\"margin:0 auto; text-align: center;\">\n    <img src=\"https://denbi-ev.de/sites/default/files/deNBIeV_Logo.svg\" alt=\"de.NBI e.V.\" style=\"width:100%;\"/>\n    <img src=\"https://kommunaltopinform.de/wp-content/uploads/2022/05/Ministerium-f-Wissenschaft-Forschg-Kunst_Logo_web.png\" alt=\"MVK\" style=\"width:60%;\"/>\n</div>\n"
   }
  },
  {
   "title": "Jobs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-jobs.upto",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-jobs",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 7 },
   "options": {
    "content": "<br/>\n\n# [European Galaxy Server](https://usegalaxy.eu)\n\n[Galaxy](https://galaxyproject.org/eu/) is an open, web-based platform for data-intensive computational\nresearch that spans beyond the life sciences. It allows researchers without programming experience\nto run analysis workflows on\ntheir data, share their results, and enable others to repeat the same analyses. Galaxy makes\nscience reproducible, facilitates sharing of data and results, and removes the hassle of installing\nsoftware tools from users.\n\nThe [European Galaxy Server](https://usegalaxy.eu) is a de.NBI and an ELIXIR service and\npart of the [ELIXIR Galaxy community](https://elixir-europe.org/communities/galaxy).\n\n\n"
   }
  },
  {
   "title": "Workflow Invocations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-users",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Datasets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-datasets",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflows",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AAI Users",
   "type": "stat",
   "description": "Users that used the [ELIXIR AAI](https://elixir-europe.org/services/compute/aai) (Authentication and Authorisation Infrastructure) to log into the European Galaxy server.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "provider" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "users-with-oidc",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Users (10 minutes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "active_users",
     "query": "SELECT \"users\" FROM \"active_users\" WHERE (\"host\" = 'sn06.galaxyproject.eu') AND $timeFilter GROUP BY \"timespan\"",
     "select": [
      [
       { "params": [ "users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  }
 ]
}