{
 "title": "EuroScienceGateway",
 "description": "Dashboard for ELIXIR monitoring",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Galaxy Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-users",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 0 },
   "options": {
    "content": "<img src=\"https://galaxyproject.org/assets/static/eosc_euro_science_gateway.d06e97a.452dcb6985a584789e3bd4c9edcb2611.svg\" alt=\"ELIXIR Europe\" style=\"width:100%;\"/>"
   }
  },
  {
   "title": "Workflow Invocations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Registered Users Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-users.upto",
     "query": "SELECT last(\"count\") FROM \"server-users.upto\" WHERE $timeFilter GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Users (last 10 minutes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "journalctl.activeusers",
     "query": "SELECT \"users\" FROM \"active_users\" WHERE (\"host\" = 'sn06.galaxyproject.eu') AND $timeFilter GROUP BY \"timespan\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-jobs.upto",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-jobs",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 11 },
   "options": {
    "content": "<br/>\n\n# [EuroScienceGateway](https://eurosciencegateway.eu)\n\nIn the past decade, many scientific domains have been transformed into data-driven disciplines relying on the exchange and\nintegration of internationally distributed data. Exploiting this data is still a laborious and largely manual task,\nprone to losses and errors, and increasingly specialized beyond most users technical capabilities. FAIR practices are\nencouraged but their adoption curve is steep. The needs for compute and data resources, tools, and application platforms\nare often domain-specific.\n\nMany scientists struggle to navigate this intricate ecosystem. Generally, researchers do not possess the computing skills\nto effectively use the HPC or Cloud platforms they need. Thus, new approaches are needed to enable all researchers,\nwith widely ranging digital skills, to efficiently use the diverse computational infrastructures available across Europe,\nfor asynchronous and for interactive applications.\n\nThe [EuroScienceGateway](https://eurosciencegateway.eu) is running various\nnational Galaxy servers and the [European Galaxy Server](https://usegalaxy.eu).\n\n\n"
   }
  },
  {
   "title": "ELIXIR AAI Users",
   "type": "stat",
   "description": "Users that used the [ELIXIR AAI](https://elixir-europe.org/services/compute/aai) (Authentication and Authorisation Infrastructure) to log into the European Galaxy server.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "provider" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "users-with-oidc",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Datasets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-datasets",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflows",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}