{
 "title": "Galaxy",
 "tags": [ "galaxy" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Galaxy Host",
    "query": "SHOW TAG VALUES FROM \"cluster.queue\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Schedulers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Condor Job States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.queue",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Queued Jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "queued" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Unscheduled Jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "The UseGalaxy.EU Queue",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "content": "## About\n\nThese graphs show you the current status of our clusters and which tools are being run on [UseGalaxy.eu](https://usegalaxy.eu). Our primary cluster is a Condor cluster running in the [deNBI cloud](https://www.denbi.de/)."
  },
  { "title": "UseGalaxy.eu Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Galaxy Running Tools",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "job_queue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "tool", "operator": "!~", "value": "/^\\//" },
      { "condition": "AND", "key": "tool", "operator": "!~", "value": "/^toolshed/" }
     ]
    },
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Allocation - Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "general compute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Allocation - Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "general compute`",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Condor Cluster Suballocation - Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "[[tag_cluster]] [[tag_group]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "cores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "!=", "value": "compute" },
      { "condition": "AND", "key": "group", "operator": "!~", "value": "/^$/" }
     ]
    }
   ]
  },
  {
   "title": "Condor Cluster Suballocation - Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "[[tag_cluster]] [[tag_group]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cluster.alloc",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group", "operator": "!=", "value": "compute" },
      { "condition": "AND", "key": "group", "operator": "!~", "value": "/^$/" }
     ]
    }
   ]
  },
  { "title": "Galaxy / Route Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Galaxy Route Timings",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "90th percentile (api)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy_page_timings.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^api.*/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "[[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy_page_timings.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^(api|web|library)/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "90th percentile (web)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "galaxy_page_timings.",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "2" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^web/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "uWSGI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Requests / time unit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Socket queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.general",
     "select": [
      [
       { "params": [ "listen_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "listen_queue" ], "type": "alias" }
      ],
      [
       { "params": [ "listen_queue_errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "listen_queue_errors" ], "type": "alias" }
      ],
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load" ], "type": "alias" }
      ],
      [
       { "params": [ "signal_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "signal_queue" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "exceptions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Busy(1)/Idle(0)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "uWSGI Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.sockets",
     "select": [
      [
       { "params": [ "can_offload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "can_offload" ], "type": "alias" }
      ],
      [
       { "params": [ "max_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max_queue" ], "type": "alias" }
      ],
      [
       { "params": [ "queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "shared" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "shared" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Harakiri count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "harakiri_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "uWSGI locks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_group]] [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.locks",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TX",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time (moving avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "[[tag_id]] @ [[tag_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "addr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uwsgi.worker",
     "select": [
      [
       { "params": [ "avg_rt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "20" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  }
 ]
}