{
 "title": "Galaxy User Statistics",
 "tags": [
  "galaxy",
  "migrated"
 ],
 "time": { "from": "now-7y", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "time_interval", "label": "Time Interval", "query": "1d,7d,30d,90d,365d" }
  ]
 },
 "panels": [
  { "title": "Total (All Time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Galaxy Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-users",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflows",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workflow Invocations",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server-workflow-invocations",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy Histories",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-histories",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-jobs",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs processing across Europe",
   "type": "grafana-worldmap-panel",
   "description": "The European Galaxy server is built on the shoulders of our European ELIXIR partners. This map is providing you some impression of how many jobs are currently processed by external clouds across Europe. Each of the circles represents one ELIXIR partner that provides compute resources via a locally hosted pulsar server. The European Galaxy server is then submitting jobs to these pulsar servers and collects the inputs as soon as finished. If one of the sites is down Galaxy will attempt to resubmit the job to some other resources.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_job_runner_name]]",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "job_runner_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT last(\"count\") FROM \"queue-overview\" WHERE (\"job_runner_name\" =~ /^pulsar_.*/ AND \"job_runner_name\" != 'condor')  AND (\"state\" = 'queued' OR \"state\" = 'running')  GROUP BY time(10m), \"job_runner_name\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=~", "value": "/^pulsar_.*/" },
      { "condition": "AND", "key": "state", "operator": "=", "value": "queued" },
      { "condition": "OR", "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "job_runner_name", "operator": "!=", "value": "condor" }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Elixir AAI Users",
   "type": "singlestat",
   "description": "Users that used the [ELIXIR AAI](https://elixir-europe.org/services/compute/aai) (Authentication and Authorisation Infrastructure) to log into the European Galaxy server.",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "provider" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "users-with-oidc",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Datasets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-datasets",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU Time (All Time)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Compute Time overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "content": "This information is calculated from the assigned `galaxy_slots` multiplied by `runtime_seconds` for each job. It will not calculate the exact CPU usage but it gives and approximation for what was allocated on our infrastructure, across multiple clouds."
  },
  {
   "title": "Pulsar DE01(Freiburg - de.NBI cloud)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_de01" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar IT01 (Bari - RECAS)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_it01" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "de.NBI Cloud",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "condor" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar DE02 (Tübingen - de.NBI cloud)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_de02" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar IT02 (Bari - RECAS)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_it02" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "AG Backofen (HPC)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "drmaa" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar DE03 (Freiburg - GPUs - de.NBI cloud)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_de03" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar BE01 (Ghent - VIB)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_be01" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar Czech Republic (CESNET)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 22 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_cz" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar PT01 (Lisbon - Tecnico ULisboa)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 22 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_pt01" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar UK01 (Diamond Light Source)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 25 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_uk01" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar FI01 (CSC)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 25 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_fi01" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Pulsar FR01 (Rennes - GenOuest bioinformatics)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 28 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "server-allocated-cpu",
     "select": [
      [
       { "params": [ "cpu_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "job_runner_name", "operator": "=", "value": "pulsar_eu_fr01" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "Recently",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-users.upto",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Jobs Over Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-jobs.upto",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
     "content": "These graphs are currently experiencing some issues, and we need to re-load the data."
    },
    {
     "title": "New HDA Datatypes / $time_interval",
     "type": "graph",
     "gridPos": { "h": 10, "w": 14, "x": 10, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "[[tag_extension]]",
       "groupBy": [
        { "params": [ "$time_interval" ], "type": "time" },
        { "params": [ "extension" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "server-hda.daily",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Jobs / $time_interval",
     "type": "graph",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$time_interval" ], "type": "time" },
        { "params": [ "job_runner_name" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "server-jobs.daily",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "job_runner_name", "operator": "!=", "value": "local" }
       ]
      }
     ]
    },
    {
     "title": "Worfklow Invocations / $time_interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$time_interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "server-workflow-invocations.daily",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "User Registrations / $time_interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$time_interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "server-users.daily",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HDAs / $time_interval",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$time_interval" ], "type": "time" },
        { "params": [ "deleted" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "server-hda.daily",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "All-Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataset Formats",
     "type": "table",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 31 },
     "targets": [
      {
       "alias": "[[tag_extension]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "extension" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-hda",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Dataset Format Disk Usage",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 7, "y": 31 },
     "targets": [
      {
       "alias": "[[tag_extension]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "extension" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-hda",
       "select": [
        [
         { "params": [ "sum" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Installed TS Repositories",
     "type": "table",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 31 },
     "targets": [
      {
       "alias": "[[tag_tool_shed]] / [[tag_owner]]",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "owner" ], "type": "tag" },
        { "params": [ "tool_shed" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-ts-repos",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Job Destinations",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 40 },
     "targets": [
      {
       "alias": "[[tag_job_runner_name]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "job_runner_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-jobs",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Job States",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 40 },
     "targets": [
      {
       "alias": "[[tag_state]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-jobs",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Datasets by Job State",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 40 },
     "targets": [
      {
       "alias": "[[tag_state]]",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-datasets",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Datasets by Job State",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 40 },
     "targets": [
      {
       "alias": "[[tag_state]]",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "state" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-datasets",
       "select": [
        [
         { "params": [ "size" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Histories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Genome Build Usage",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
     "targets": [
      {
       "alias": "[[tag_genome_build]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "genome_build" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "server-histories",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}