{
 "title": "Galaxy Database",
 "tags": [
  "migrated",
  "infrastructure"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "tables",
    "label": "Tables",
    "query": "show tag values with key = \"relname\""
   },
   {
    "name": "DB",
    "label": "Tables",
    "query": "show tag values with key = \"db\""
   }
  ]
 },
 "panels": [
  {
   "title": "blk_read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "[[tag_db]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "blks_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PG Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg-cache-hit",
     "select": [
      [
       { "params": [ "ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sequential Scans",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg-stat-user-tables",
     "select": [
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "δTable Size Change/δt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg-stat-user-tables",
     "select": [
      [
       { "params": [ "n_live_tup" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "δDead Tuples / δtime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg-stat-user-tables",
     "select": [
      [
       { "params": [ "n_dead_tup" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autovacuums",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg-stat-user-tables",
     "select": [
      [
       { "params": [ "autovacuum_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Table Sizes",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg-table-size",
     "select": [
      [
       { "params": [ "table_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Sizes",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "alias": "[[tag_relname]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "relname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg-table-size",
     "select": [
      [
       { "params": [ "index_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$DB metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Tuples Modified",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "deleted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_inserted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "inserted" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_updated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "updated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_db]]:commit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$DB$/" }
     ]
    },
    {
     "alias": "[[tag_db]]:rollback",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_rollback" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Tuples Fetched",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "fetched" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_returned" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "returned" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Backends",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "numbackends" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  },
  {
   "title": "Conflicts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$DB$/" }
     ]
    }
   ]
  }
 ]
}