{
 "title": "Histories",
 "tags": [ "API" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Histories", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "/api/histories/{history_id}/contents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean",
     "measurement": "denbi.galaxy.freiburg.api.history_contents.index",
     "query": "SELECT \"mean\" FROM \"main_api_history_contents_index\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "denbi.galaxy.freiburg.api.history_contents.index",
     "query": "SELECT percentile(\"mean\", 95) FROM \"main_api_history_contents_index\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "/api/histories/{history_id}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean",
     "measurement": "denbi.galaxy.freiburg.api.histories.index",
     "query": "SELECT \"mean\" FROM \"main_api_tools_index\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "denbi.galaxy.freiburg.api.histories.index",
     "query": "SELECT percentile(\"mean\", 95) FROM \"main_api_histories_show\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "/api/histories/{history_id}/contents/{id}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean",
     "measurement": "denbi.galaxy.freiburg.api.history_contents.show",
     "query": "SELECT \"mean\" FROM \"main_api_history_contents_show\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "denbi.galaxy.freiburg.api.history_contents.show",
     "query": "SELECT percentile(\"mean\", 95) FROM \"main_api_history_contents_show\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUT /api/histories/{history_id}/contents/datasets/{id}",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean",
     "measurement": "denbi.galaxy.freiburg.api.history_contents.update",
     "query": "SELECT \"mean\" FROM \"main_api_history_contents_update\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "denbi.galaxy.freiburg.api.history_contents.update",
     "query": "SELECT percentile(\"mean\", 95) FROM \"main_api_history_contents_update\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "/api/histories",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean",
     "measurement": "denbi.galaxy.freiburg.api.histories.index",
     "query": "SELECT \"mean\" FROM \"main_api_tools_index\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "denbi.galaxy.freiburg.api.histories.index",
     "query": "SELECT percentile(\"mean\", 95) FROM \"main_api_histories_index\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "histories list operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean",
     "measurement": "denbi.galaxy.freiburg.web.history.list",
     "query": "SELECT \"mean\" FROM \"main_web_history_list\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "denbi.galaxy.freiburg.web.history.list",
     "query": "SELECT percentile(\"mean\", 95) FROM \"main_web_history_list\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "/api/histories/{history_id}/contents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "mean",
     "measurement": "denbi.galaxy.freiburg.api.history_contents.index",
     "query": "SELECT \"mean\" FROM \"main_api_history_contents_index\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "95th",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "denbi.galaxy.freiburg.api.history_contents.index",
     "query": "SELECT percentile(\"mean\", 95) FROM \"main_api_history_contents_index\" WHERE $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  }
 ]
}