{
 "title": "IEv2",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ies",
    "query": "SHOW TAG VALUES FROM \"queue-overview\" WITH KEY = \"tool_id\""
   }
  ]
 },
 "panels": [
  {
   "title": "$ies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 0, "y": 0 },
   "repeat": "ies",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/interactive_tool_$ies/" }
     ]
    }
   ]
  },
  {
   "title": "$ies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/interactive_tool_$ies/" }
     ]
    }
   ]
  },
  {
   "title": "$ies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/interactive_tool_$ies/" }
     ]
    }
   ]
  },
  {
   "title": "$ies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/interactive_tool_$ies/" }
     ]
    }
   ]
  },
  {
   "title": "$ies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/interactive_tool_$ies/" }
     ]
    }
   ]
  },
  {
   "title": "$ies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/interactive_tool_$ies/" }
     ]
    }
   ]
  },
  {
   "title": "$ies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/interactive_tool_$ies/" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^cn/" }
     ]
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^cn/" }
     ]
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_image]] / [[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_image]] / [[tag_container_name]]",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "rss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_container_image]] / [[tag_container_name]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "container_image" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Galaxy Running Tools",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_tool_id]]/[[tag_tool_version]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "tool_id" ], "type": "tag" },
      { "params": [ "tool_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" },
      { "condition": "AND", "key": "tool_id", "operator": "=~", "value": "/^interactive/" }
     ]
    }
   ]
  },
  {
   "title": "Containers Running",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}