{
 "title": "Job visualization",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Data Upload / Hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "general compute`",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "upload-gb-in-past-hour",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "HTCondor job queue - overview",
   "type": "stat",
   "description": "Gives an overview of the current status of the jobs in the HTCondor queue.",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "schedd" ], "type": "tag" }
     ],
     "measurement": "cluster.queue",
     "query": "SELECT mean(\"count\") FROM \"cluster.queue\" WHERE (\"host\" = 'maintenance.galaxyproject.eu' AND \"schedd\" = 'sn06.galaxyproject.eu') AND $timeFilter GROUP BY time($__interval), \"state\", \"schedd\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" },
      { "condition": "AND", "key": "schedd", "operator": "=~", "value": "/^$Schedd$/" }
     ]
    }
   ]
  },
  {
   "title": "Job queue",
   "type": "timeseries",
   "description": "Time-series showing the status of Galaxy jobs.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'running') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "running" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'queued') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "queued" }
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "query": "SELECT sum(\"count\") FROM \"queue-overview\" WHERE (\"state\" = 'new') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 7 },
   "options": {
    "content": "# Fair Resource Distribution\nRegardless of how many jobs a user starts, our fair scheduling system distributes the resources evenly. This means that even if there are 100,000 jobs in the queue, starting a single job can be done quickly. \n\n"
   }
  },
  {
   "title": " Queued jobs (with or without condor ids)",
   "type": "timeseries",
   "description": "Shows the distribution of jobs in the queued state, categorized as processed and unprocessed depending on whether they have received an external  (HTCondor) ID or not.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_group]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "jobs-queued",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "maintenance.galaxyproject.eu" }
     ]
    }
   ]
  }
 ]
}