{
 "title": "MIra playground",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "MQ",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_node\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Tool-usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tool-usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Tasks Currently Executing at Worker",
   "type": "graph",
   "description": "This panel shows number of tasks currently executing at worker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flower_worker_number_of_currently_executing_tasks",
     "groupBy": [
      { "params": [ "worker" ], "type": "tag" }
     ],
     "legendFormat": "{{worker}}",
     "measurement": "flower_worker_number_of_currently_executing_tasks",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  },
  {
   "title": "Celery Disk",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "[[tag_fstype]] @ [[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  },
  {
   "title": "Rabbit Disk",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 5, "x": 6, "y": 8 },
   "targets": [
    {
     "alias": "[[tag_fstype]] @ [[tag_path]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mq.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Celery Worker Prefetched Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "flower_worker_prefetched_tasks",
     "query": "SELECT derivative(\"gauge\", 10s) FROM \"flower_events_created\" WHERE (\"host\" = 'celery-0.galaxyproject.eu.novalocal')",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  },
  {
   "title": "Galaxy Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "server-users",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "measurement": "zfs",
     "select": [
      [
       { "params": [ "wops" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "zfs2f.galaxyproject.eu" }
     ]
    },
    {
     "measurement": "zfs",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ " / 10000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "zfs2f.galaxyproject.eu" }
     ]
    },
    {
     "measurement": "zfs",
     "select": [
      [
       { "params": [ "compr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "zfs2f.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Active Users (10 minutes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "timespan" ], "type": "tag" }
     ],
     "measurement": "active_users",
     "query": "SELECT mean(\"value\") FROM \"active_users\"",
     "select": [
      [
       { "params": [ "users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Celery0 System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Load" } },
   "targets": [
    {
     "alias": "I/O Wait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "active" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  },
  {
   "title": "Celery Worker Status",
   "type": "stat",
   "description": "This panel shows status of celery workers. 1 = online, 0 = offline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flower_worker_online",
     "groupBy": [
      { "params": [ "worker" ], "type": "tag" }
     ],
     "legendFormat": "{{ worker }}",
     "measurement": "flower_worker_online",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Task Runtime at Worker",
   "type": "graph",
   "description": "This panel shows average task runtime at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "flower_task_runtime_seconds",
     "select": [
      [
       { "params": [ "0.01" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  },
  {
   "title": "Rabbit test",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "measurement": "rabbitmq_channel_messages_published_total",
     "query": "SELECT non_negative_derivative(\"counter\", [h]) FROM \"rabbitmq_channel_messages_published_total\" WHERE (\"host\" = 'mq.galaxyproject.eu')",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mq.galaxyproject.eu" }
     ]
    },
    {},
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_channel_messages_unacked",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mq.galaxyproject.eu" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_consumers",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mq.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Currently Running and Queued Jobs vs Mean Upload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "job_queue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    },
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!=", "value": "new" }
     ]
    },
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upload-gb-in-past-hour",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task Prefetch Time at Worker",
   "type": "graph",
   "description": "This panel shows task prefetch time at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flower_task_prefetch_time_seconds",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" }
     ],
     "legendFormat": "{{task}}, {{worker}}",
     "measurement": "flower_task_prefetch_time_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "host",
       "operator": "=",
       "value": "celery-0.galaxyproject.eu.novalocal"
      }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "kernel",
     "select": [
      [
       { "params": [ "interrupts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn06.galaxyproject.eu" }
     ]
    }
   ]
  }
 ]
}