{
 "title": "Public Galaxy Servers",
 "tags": [ "pgs" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "This dashboard shows information about some of the \n<a href=\"https://github.com/martenson/public-galaxy-servers/\">public galaxy servers</a>. \n To build the dashboard, we made requests to these public servers' APIs every hour asking for their\n configuration information. We then aggregated that information into dashboards. Please note that \n uptime percentages may not be perfectly accurate. Additionally, response times may be different than \n what you see as all requests were made from a server in Freiburg, Germany. The\n<a target=\"_blank\" href=\"https://stats.galaxyproject.eu/raw/\">collected data</a> is freely accessible \n from our server so everyone can build off of it (license CC0). If your server is missing from the\n dashboard or you believe the data is wrong, just open an\n<a href=\"https://github.com/martenson/public-galaxy-servers/issues\">issue</a> or a \n<a href=\"https://github.com/martenson/public-galaxy-servers/edit/master/servers.csv\">PR</a> with the\n relevant information. We've also made\n <a href=\"https://stats.galaxyproject.eu/raw/badges/\" target=\"_blank\">uptime badges</a> available\n if you want to show off. Feel free to embed a link directly to the image, e.g.\n  <img src=\"https://stats.galaxyproject.eu/raw/badges/UseGalaxy_eu.svg\" />  "
  },
  {
   "title": "Galaxies Across the World",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 4 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_location",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server",
     "query": "SELECT mean(\"value\") FROM \"server\" WHERE $timeFilter GROUP BY time($__interval), \"location\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "30 Day Uptime",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "description": "Time for the server to respond to our request. 40 indicates a timeout / inability to reach the server.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requiring Log-in",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_require_login]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "require_login" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "require_login", "operator": "=", "value": "True" },
      { "condition": "OR", "key": "require_login", "operator": "=", "value": "False" }
     ]
    }
   ]
  },
  {
   "title": "Version Distribution",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 26 },
   "targets": [
    {
     "alias": "[[tag_version]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Enabling Quotas",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_enable_quotas]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "enable_quotas" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "enable_quotas", "operator": "=", "value": "False" },
      { "condition": "OR", "key": "enable_quotas", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Allowing User Creation",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_allow_user_creation]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "allow_user_creation" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "allow_user_creation", "operator": "=", "value": "False" },
      { "condition": "OR", "key": "allow_user_creation", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Allowing User Dataset Purge",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_allow_user_dataset_purge]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "allow_user_dataset_purge" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "allow_user_dataset_purge", "operator": "=", "value": "False" },
      { "condition": "OR", "key": "allow_user_dataset_purge", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Supporting OpenID",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 26 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_enable_openid]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "enable_openid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "server",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "enable_openid", "operator": "=", "value": "False" },
      { "condition": "OR", "key": "enable_openid", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Galactic Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "allow_user_creation" ], "type": "tag" },
      { "params": [ "enable_quotas" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "require_login" ], "type": "tag" },
      { "params": [ "allow_user_creation" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "enable_communication_server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "server",
     "query": "SELECT last(\"value\") FROM \"server\" WHERE \"responding\" = 'True' AND \"galaxy\" = 'True' AND $timeFilter GROUP BY time($__interval), \"name\", \"version\", \"allow_user_creation\", \"enable_quotas\", \"location\", \"require_login\", \"allow_user_creation\", \"enable_communication_server\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "responding", "operator": "=", "value": "True" },
      { "condition": "AND", "key": "galaxy", "operator": "=", "value": "True" }
     ]
    }
   ]
  }
 ]
}