{
 "title": "Queue depletion",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "δ(Job Queue per handler)/δt",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_handler]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "handler" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "queue-overview",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "$__interval" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=", "value": "new" },
      { "condition": "AND", "key": "handler", "operator": "!=", "value": "_default_" }
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_handler]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "handler" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  },
  {
   "title": "load5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_handler]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "handler" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "sn04.bi.uni-freiburg.de" }
     ]
    }
   ]
  }
 ]
}