{
 "title": "RabbitMQ - Galaxy",
 "tags": [
  "infrastructure",
  "migrated"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mqs",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_node\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "proc_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "sockets_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "sockets_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "channels" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_queue]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consumers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "messages_acked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "acked" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_delivered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "delivered" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_published" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "published" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_ready" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ready" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_unacked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "unacked" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "fd_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "fd_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "exchanges" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Messages galaxy_core_exchange",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "repeat": "vhost",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_exchange",
     "select": [
      [
       { "params": [ "messages_publish_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_publish_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "galaxy_core_exchange" }
     ]
    }
   ]
  },
  {
   "title": "Ack'd Messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_queue]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_ack" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "UNAck'd Messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_queue]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_unack" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Redelivered Messages",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_queue]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_redeliver" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  }
 ]
}