{
 "title": "RabbitMQ - Pulsar",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mqs",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_node\" WITH KEY = \"host\""
   },
   {
    "name": "vhost",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_queue\" WITH KEY = \"vhost\""
   },
   { "name": "time_interval", "query": "10s,30s,1m,2m,5m,10m,60m" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "proc_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "sockets_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "sockets_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "select": [
      [
       { "params": [ "fd_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "fd_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "messages_acked" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "acked" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_delivered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "delivered" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_unacked" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "unacked" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "exchanges" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "select": [
      [
       { "params": [ "channels" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Messages $vhost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "repeat": "vhost",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_exchange",
     "select": [
      [
       { "params": [ "messages_publish_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_publish_out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "exchange", "operator": "=", "value": "pulsar" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumers $vhost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "repeat": "vhost",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_queue]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consumers" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Messages $vhost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "repeat": "vhost",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "deliver",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_deliver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "delivered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__setup" }
     ]
    },
    {
     "alias": "ack",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_ack" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "ack" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__setup" }
     ]
    },
    {
     "alias": "unack",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_unack" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "unack" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__setup" }
     ]
    }
   ]
  },
  {
   "title": "Job Kill Messages $vhost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "repeat": "vhost",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "deliver",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_deliver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "delivered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__kill" }
     ]
    },
    {
     "alias": "ack",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_ack" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "ack" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__kill" }
     ]
    },
    {
     "alias": "unack",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_unack" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "unack" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__kill" }
     ]
    }
   ]
  },
  {
   "title": "Job Status Messages $vhost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "repeat": "vhost",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "deliver",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_deliver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "delivered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__status_update" }
     ]
    },
    {
     "alias": "ack",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_ack" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "ack" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__status_update" }
     ]
    },
    {
     "alias": "unack",
     "groupBy": [
      { "params": [ "$time_interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_unack" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$time_interval" ], "type": "non_negative_derivative" },
       { "params": [ "unack" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$mqs$/" },
      { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/$vhost$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "pulsar__status_update" }
     ]
    }
   ]
  }
 ]
}