{
 "title": "Traefik",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Traefik Hosts",
    "query": "SHOW TAG VALUES FROM \"traefik\" WITH KEY = \"host\""
   },
   {
    "name": "services",
    "query": "SHOW TAG FROM \"traefik.traefik_service_requests_total\"  WHERE (\"host\" =~ /^$host$/), \"service\""
   }
  ]
 },
 "panels": [
  {
   "title": "Services (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "traefik",
     "query": "SELECT derivative(first(traefik_service_requests_total), 1s) FROM traefik WHERE time > now() - 1h AND (\"host\" =~ /^$host$/) GROUP BY time(10s), \"service\"",
     "select": [
      [
       { "params": [ "traefik_service_requests_total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests per Entrypoint (Bjoern)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\"}[1m])) by (entrypoint)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{entrypoint}}",
     "measurement": "traefik",
     "query": "SELECT mean(\"traefik_service_requests_total\"), mean(\"traefik_service_requests_total\")  FROM \"traefik\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "traefik_service_requests_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik",
     "query": "SELECT mean(\"traefik_router_requests_total\") FROM \"traefik\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "traefik_router_requests_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "tcp established mean per minute",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "select": [
      [
       { "params": [ "tcp_established" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "traefik.flyingrabb.it" }
     ]
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\"}[1m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}",
     "query": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\\\"$entrypoint\\\"}[1m])) by (entrypoint)"
    }
   ]
  },
  {
   "title": "Service requests total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "service requests per 10 sec",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "router" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "traefik",
     "query": "SELECT distinct(\"traefik_service_requests_total\") FROM \"traefik\" WHERE (\"host\" = 'traefik.flyingrabb.it') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "traefik_entrypoint_requests_total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "traefik.flyingrabb.it" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "traefik.flyingrabb.it" }
     ]
    }
   ]
  }
 ]
}